"""Download and validate large Colab artifact packages.

This script automates the post-processing workflow for packages generated by
`colab/notebooks/colab_wikipedia_preprocessing.ipynb` Step 7A:
1) Download `download_packages` with rclone or gsutil
2) Verify SHA-256 checksums for every split part
3) Reconstruct `.tar.gz` archives from part files
4) Optionally extract reconstructed archives

Typical usage:
  python scripts/download_colab_packages.py \
      --source "gdrive:AIST-FYP-colab-preprocess/<run_folder>/download_packages" \
      --dest "D:/AIST-FYP-downloads/download_packages" \
      --tool rclone
"""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import subprocess
import sys
import tarfile
from pathlib import Path


MANIFEST_FILENAME = "package_manifest.json"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Download, verify, and reconstruct Colab split packages.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Full flow with rclone: download + verify + reconstruct
  python scripts/download_colab_packages.py \
      --source "gdrive:AIST-FYP-colab-preprocess/<run_folder>/download_packages" \
      --dest "D:/AIST-FYP-downloads/download_packages" \
      --tool rclone

  # Verify + reconstruct from already-downloaded files
  python scripts/download_colab_packages.py \
      --dest "D:/AIST-FYP-downloads/download_packages" \
      --skip-download

  # Verify only
  python scripts/download_colab_packages.py \
      --dest "D:/AIST-FYP-downloads/download_packages" \
      --skip-download \
      --skip-reconstruct
        """,
    )

    parser.add_argument("--source", type=str, default=None, help="Remote package folder path")
    parser.add_argument("--dest", type=Path, required=True, help="Local destination directory")
    parser.add_argument("--tool", choices=["rclone", "gsutil"], default="rclone", help="Transfer CLI")
    parser.add_argument("--skip-download", action="store_true", help="Skip transfer step")
    parser.add_argument("--skip-verify", action="store_true", help="Skip checksum verification")
    parser.add_argument("--skip-reconstruct", action="store_true", help="Skip reconstruction of tar.gz")
    parser.add_argument("--extract", action="store_true", help="Extract reconstructed tar.gz archives")
    parser.add_argument(
        "--keep-archive",
        action="store_true",
        help="Keep reconstructed tar.gz after extraction (default: remove when --extract)",
    )
    parser.add_argument("--dry-run", action="store_true", help="Print actions without running them")
    return parser.parse_args()


def run_command(command: list[str], dry_run: bool) -> None:
    printable = " ".join(command)
    print(f"$ {printable}")
    if dry_run:
        return

    process = subprocess.Popen(
        command,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1,
    )
    assert process.stdout is not None
    for line in process.stdout:
        print(line, end="")
    process.wait()

    if process.returncode != 0:
        raise RuntimeError(f"Command failed ({process.returncode}): {printable}")


def ensure_cli_available(cli_name: str) -> None:
    if shutil.which(cli_name) is None:
        raise FileNotFoundError(
            f"Required CLI '{cli_name}' was not found in PATH. "
            f"Install it and retry."
        )


def download_packages(source: str, destination: Path, tool: str, dry_run: bool) -> None:
    destination.mkdir(parents=True, exist_ok=True)

    if tool == "rclone":
        ensure_cli_available("rclone")
        command = [
            "rclone",
            "copy",
            "--progress",
            "--retries",
            "10",
            "--low-level-retries",
            "20",
            "--checksum",
            source,
            str(destination),
        ]
        run_command(command, dry_run=dry_run)
        return

    ensure_cli_available("gsutil")
    command = ["gsutil", "-m", "cp", "-r", source, str(destination)]
    run_command(command, dry_run=dry_run)


def resolve_manifest_root(destination: Path) -> Path:
    direct = destination / MANIFEST_FILENAME
    nested = destination / "download_packages" / MANIFEST_FILENAME

    if direct.exists():
        return destination
    if nested.exists():
        return destination / "download_packages"

    matches = list(destination.rglob(MANIFEST_FILENAME))
    if len(matches) == 1:
        return matches[0].parent

    if len(matches) > 1:
        raise FileNotFoundError(
            "Multiple package manifests found. Please point --dest to the exact package root."
        )

    raise FileNotFoundError(
        f"{MANIFEST_FILENAME} not found. Ensure download completed and --dest is correct."
    )


def sha256_of_file(file_path: Path) -> str:
    hasher = hashlib.sha256()
    with open(file_path, "rb") as file_handle:
        while True:
            block = file_handle.read(8 * 1024 * 1024)
            if not block:
                break
            hasher.update(block)
    return hasher.hexdigest()


def parse_checksum_file(checksum_path: Path) -> list[tuple[str, str]]:
    rows: list[tuple[str, str]] = []
    for raw_line in checksum_path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line:
            continue
        digest, filename = line.split("  ", 1)
        rows.append((digest.strip(), filename.strip()))
    return rows


def verify_parts(manifest_root: Path, artifacts: list[dict]) -> None:
    print("\n[Verify] Checking SHA-256 for all parts...")
    for artifact in artifacts:
        artifact_dir_name = Path(artifact["archive_dir"]).name
        artifact_local_dir = manifest_root / artifact_dir_name
        checksums_path = artifact_local_dir / "checksums.sha256"

        if not checksums_path.exists():
            raise FileNotFoundError(f"Missing checksums file: {checksums_path}")

        expected_rows = parse_checksum_file(checksums_path)
        print(f"- {artifact_dir_name}: {len(expected_rows)} part(s)")

        for digest, filename in expected_rows:
            part_path = artifact_local_dir / filename
            if not part_path.exists():
                raise FileNotFoundError(f"Missing part file: {part_path}")
            actual_digest = sha256_of_file(part_path)
            if actual_digest != digest:
                raise ValueError(
                    f"Checksum mismatch for {part_path.name}: expected {digest}, got {actual_digest}"
                )



def reconstruct_archives(
    manifest_root: Path,
    artifacts: list[dict],
    extract_archives: bool,
    keep_archive: bool,
) -> None:
    print("\n[Reconstruct] Joining split parts into tar.gz archives...")
    for artifact in artifacts:
        source_name = Path(artifact["source_path"]).name
        artifact_dir_name = Path(artifact["archive_dir"]).name
        artifact_local_dir = manifest_root / artifact_dir_name

        output_archive = artifact_local_dir / f"{source_name}.tar.gz"
        with open(output_archive, "wb") as output_handle:
            for part_name in artifact["parts"]:
                part_path = artifact_local_dir / part_name
                if not part_path.exists():
                    raise FileNotFoundError(f"Missing part file during reconstruction: {part_path}")
                with open(part_path, "rb") as input_handle:
                    shutil.copyfileobj(input_handle, output_handle, length=8 * 1024 * 1024)

        print(f"- Reconstructed: {output_archive}")

        if extract_archives:
            extract_dir = artifact_local_dir / "extracted"
            extract_dir.mkdir(parents=True, exist_ok=True)
            with tarfile.open(output_archive, "r:gz") as tar_handle:
                tar_handle.extractall(path=extract_dir)
            print(f"  Extracted to: {extract_dir}")
            if not keep_archive:
                output_archive.unlink(missing_ok=True)
                print("  Removed reconstructed archive after extraction")


def main() -> None:
    args = parse_args()

    destination = args.dest.resolve()

    if not args.skip_download:
        if not args.source:
            raise ValueError("--source is required unless --skip-download is set")
        print("[Step] Downloading packages...")
        download_packages(source=args.source, destination=destination, tool=args.tool, dry_run=args.dry_run)

    if args.dry_run:
        print("\nDry run complete.")
        return

    manifest_root = resolve_manifest_root(destination)
    manifest_path = manifest_root / MANIFEST_FILENAME
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    artifacts: list[dict] = manifest.get("artifacts", [])

    if not artifacts:
        raise ValueError(f"No artifacts found in manifest: {manifest_path}")

    print(f"\n[Info] Manifest: {manifest_path}")
    print(f"[Info] Artifact count: {len(artifacts)}")

    if not args.skip_verify:
        verify_parts(manifest_root=manifest_root, artifacts=artifacts)
        print("[Verify] All checksums passed")

    if not args.skip_reconstruct:
        reconstruct_archives(
            manifest_root=manifest_root,
            artifacts=artifacts,
            extract_archives=args.extract,
            keep_archive=args.keep_archive,
        )

    print("\nDone.")


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        sys.exit(1)
